DefBuilder(CCUserDataChangeUp, 0xFFF1);
DefBuilder(CCPackChange, 0xFFF2);
DefBuilder(CCHeroEqChange, 0xFFF3);
DefBuilder(CCTeamChange, 0xFFF4);
DefBuilder(CCHeroPanelOpen, 0xFFF5);
DefBuilder(CCHeroLevelUp, 0xFFF6);
DefBuilder(CCVIPLevelChange, 0xFFF7);
DefBuilder(CSendItemToChat, 0xFFF8);
DefBuilder(CCSendDemonToMassage, 0xFFF9);
